#include "global.h"

const char* transponder_php=
"<?php \r\n"
//error_reporting(E_ERROR);
// PHP_VERSION_ID доступна в версиях PHP 5.2.7 и выше. Если версия ниже, можно её сэмулировать
"if (!defined('PHP_VERSION_ID')) {\r\n"
"    $version = explode('.', PHP_VERSION);\r\n"
"    define('PHP_VERSION_ID', ($version[0] * 10000 + $version[1] * 100 + $version[2]));\r\n"
	// ver < 5.2.7 if (PHP_VERSION_ID < 50207)
"}\r\n"
//key=AAA&cmd=BBB&arg=CCC&ext=EEE[&dev=DDD for device]
"if (!defined('TRANSPONDER_VERSION')){define('TRANSPONDER_VERSION','" _VERSION_ "');}\r\n"
"if (!defined('AD')) {define('AD','access denied');}\r\n"
"if (!defined('PHP_EOL')) {define('PHP_EOL','\r\n');}\r\n" //Доступно с PHP 5.0.2

"$dev= isset($_GET['dev'])?$_GET['dev']:'';$key= isset($_GET['key'])?$_GET['key']:'';\r\n"
"$access= isset($_GET['access'])?$_GET['access']:(isset($_POST['access'])?$_POST['access']:'');\r\n"
"$cmd= isset($_GET['cmd'])?$_GET['cmd']:(isset($_POST['cmd'])?$_POST['cmd']:'');\r\n"
"$arg= isset($_GET['arg'])?$_GET['arg']:(isset($_POST['arg'])?$_POST['arg']:'');\r\n"
"$ext= isset($_GET['ext'])?$_GET['ext']:(isset($_POST['ext'])?$_POST['ext']:'');\r\n"
"$logfile='log'.dev_name().'.png';\r\n"
"$ukey= isset($_GET['ukey'])?$_GET['ukey']:'';\r\n"
//echo '$logfile='.$logfile.'<br>';	
"$unixtime=time();//int:количество секунд, прошедших с начала эпохи Unix (1 января 1970 00:00:00 GMT) до текущего времени.\r\n"
"$tzone='UTC';$maxlogs=32;$logline=1;\r\n"		//временная зона,максимальное количество строк запросов(логировние),начальная строка для логирования
"$adminkey='inferno';$lang='en';\r\n"

"if(isset($_POST['guestkey']) && !isset($_GET['key']))\r\n"
"{\r\n"
"	$key=$_POST['guestkey'];\r\n"
"	if($logfile=='log.png')$logfile='log'.dev_name().'.png';\r\n"
"	if($access=='access')$access='';if($cmd=='cmd')$cmd='';if($arg=='arg')$arg='';if($ext=='ext')$ext='';\r\n"
	//echo '<br>POST key='.$key. ' logfile='.$logfile;
"}\r\n"

"if(file_exists($logfile))\r\n" 
"{\r\n"
"	$lines=file($logfile);\r\n" 		//Считываем весь файл в массив
"	if(count($lines)>=$logline)list($tzone,$maxlogs,$logline,$adminkey,$lang)=explode(';',$lines[0]);else unlink ($logfile);\r\n"
"	$adminkey=trim($adminkey);$lang=trim($lang);\r\n"
"}\r\n"
// установка временной зоны по умолчанию. Доступно с PHP 5.1
"if(PHP_VERSION_ID >= 50100){ if(date_default_timezone_set($tzone)==false && file_exists($logfile)){unlink($logfile);$tzone='UTC';} }\r\n"
//$reqtime=date('Y-m-d H:i:s T');// выведет примерно следующее:2021-02-12 20:42:12 +03
"$reqtime=date('Y-m-d H:i:s T');\r\n"// выведет : Mon, 15 Aug 2005 15:12:46 UTC
//-----------------------------------
"function wrap_output($_str)\r\n"
"{\r\n"
"	global $dev;\r\n"
"	return '<transponder'.$dev.\">\".$_str.'</transponder'.$dev.\">\";\r\n"
"}\r\n"
//-----------------------------------
"switch ($access){\r\n"
"case 'get_server':print wrap_output(isset($_SERVER[$arg]) ? $_SERVER[$arg] : 'error');break;\r\n"
"case 'get_my_ip':print wrap_output(isset($_SERVER['HTTP_X_FORWARDED_FOR']) ? $_SERVER['HTTP_X_FORWARDED_FOR'] : $_SERVER['REMOTE_ADDR']);break;\r\n"
"case 'get_transponder':print wrap_output(TRANSPONDER_VERSION);break;\r\n"
"case 'get_unixtime':print wrap_output('unixtime='.$unixtime);break;\r\n"
"case 'get_logscreen':if($key!=$dev && $key!=$adminkey){print(wrap_output(AD));break;}else out_scrlog($logfile);return;\r\n"
"case 'transfer':print wrap_output(save_request_to_file($logfile,$key,$cmd,$arg,$ext));check_if_file_correct($logfile);break;\r\n"
"case 'receive':print wrap_output(get_request_from_file($logfile));check_if_file_correct($logfile);break;\r\n"
"case 'delete_line':print wrap_output(delete_line_in_file($_file,$arg));break;\r\n"
"case 'delete_request':print wrap_output(delete_request_in_file($_file,$ukey,$arg));break;"//удалить линию по ключу и времени
"case 'set_response':print wrap_output(set_response_in_file($logfile,$ukey,$arg,$ext));break;\r\n"
"case 'get_response':print wrap_output(get_response_from_file($logfile,$key,$arg));break;\r\n"
"case 'set_tzone': $tzone=$arg;break;\r\n"//?access=set_tzone&key=48174164150128240&dev=48174164150128240&arg=[tzone]
"case 'set_maxlogs':$maxlogs=$arg;break;\r\n"//?access=set_maxlogs&key=48174164150128240&dev=48174164150128240&arg=[maxlogs]
"case 'set_logline':$logline=$arg;break;\r\n"//?access=set_logline&key=48174164150128240&dev=48174164150128240&arg=[logline]
"case 'set_adminkey':$adminkey=$arg;break;\r\n"//?access=set_adminkey&key=48174164150128240&dev=48174164150128240&arg=rvscode
"case 'set_lang':$lang=$arg;break;\r\n"//?access=set_lang&key=48174164150128240&dev=48174164150128240&arg=ru
"case 'get_filesize':if($key!=$dev && $key!=$adminkey){print(wrap_output(AD));break;}\r\n"
"		if (file_exists($arg)) print wrap_output(filesize($arg));else print wrap_output('no file');break;\r\n"
"case 'delete_file':if($key!=$dev && $key!=$adminkey)print(wrap_output(AD)); else { unlink ($arg);print wrap_output('success');}	break;\r\n"
"default : break;//break;//print(wrap_output(AD)); break;\r\n"
"}\r\n"
	
"if($access=='set_tzone' || $access=='set_maxlogs' || $access=='set_logline' || $access=='set_adminkey' || $access=='set_lang')\r\n"
"{\r\n"
"	if($key!=$dev && $key!=$adminkey){print(wrap_output(AD));return;}\r\n"
"	if($access=='set_tzone' && PHP_VERSION_ID >= 50100)date_default_timezone_set($tzone);\r\n"
"	$resp=replace_line_in_file($logfile,0,$tzone.';'.$maxlogs.';'.$logline.';'.$adminkey.';'.$lang);\r\n"
"	if(isset($_POST['guestkey']) && $_POST['guestkey']==$adminkey)return accessForm($resp,false,false,true);\r\n"
"	if($key==$dev)print(wrap_output($resp));\r\n"
"}\r\n"
"if($key==dev_name() && $dev==dev_name())return;\r\n"
//-----------------------------------
"function out_scrlog($_file)\r\n"
"{\r\n"
"  global $arg,$ext;\r\n"
"  ?>\r\n"
"  <html><body bgcolor='#000000'>\r\n"
"  <?php\r\n"
"  if(!file_exists($_file))echo '<p style=\"font-size: 100%; color:rgb(255,0,0)\">empty file</p>';\r\n"
"  $lines = file($_file);\r\n"
"  $color='#00af00';if($arg!='')$color=$arg;\r\n"
"  for($i=0;$i<count($lines);$i++)\r\n"
"  {\r\n"
"    $repl=' ';$str='';\r\n"
"    if($ext=='' || $ext=='ext')$str=str_replace(';',$repl,$lines[$i]);else $str=str_replace(';',$ext,$lines[$i]);\r\n"
"    ?> <div style='font-size: 100%; color:<?php echo $color ?>' > <?php echo ($i+1).': '.$str ?> </div> <?php //html + php\r\n"
"  }\r\n"
"  ?>\r\n"
"  </body></html>\r\n"
"  <?php\r\n"
"}\r\n"
//-----------------------------------
"function transl($_word)\r\n" 
"{\r\n"
"	global $lang;\r\n"
"	$lang = strtolower($lang);\r\n"
"	$tr=str_replace('_',' ',$_word);\r\n"
"	switch($lang)\r\n"
"	{\r\n"
"		case 'russian':case 'ru':\r\n"
"			switch($tr)\r\n"
"			{\r\n"
"				case 'error':return '☠';\r\n"//ошибка';\r\n"
"				case 'success':return 'ツ';\r\n"//успешно';\r\n"
"				case 'processed':return 'в обработке';\r\n"
"				case 'input command':return 'введите команду';\r\n"
"				case 'transfer error.retry.':return '¯\\(°_o)/¯';\r\n"//'ошибка передачи.повторите.';\r\n"
"				case 'response not found.retry.':return 'ответ не найден.повторите.';\r\n"
"				case 'no reply received.retry.':return 'ответ не получен.повторите.';\r\n"
"				case 'error: key not found':return '¯\\_(ツ)_/¯';\r\n"//ошибка: ключ не найден';\r\n"
"				case 'ok':case 'OK':return 'ツ';\r\n"
"				case 'enter access key':return 'введите код';\r\n"
"				case 'ENTER ACCESS KEY':return 'ВВЕДИТЕ КОД';\r\n"
"				case 'Estonian server - no way faster.':return 'Эстонский сервер.Быстрее-никак.';\r\n"
"				case 'Hello! Do you believe in God?':return '¯\\(°_o)/¯';\r\n"//Здравствуйте!Вы верите в Бога?';\r\n"
"				case \"We've rated your speed.\":return 'Мы оценили вашу скорость.';\r\n"
"				case 'Slow down - bend the button :)':return '(◣_◢)';\r\n"//Сбавьте скорость-погнёте кнопку:)';\r\n"
"				case 'do you like speed?':return 'любите скорость?';\r\n"
"			}\r\n"
"			return $tr;\r\n"
"			break;\r\n"
"		case 'en':case 'eng':case 'english':default:return $tr;\r\n"
"	}\r\n"
"}\r\n"
//-----------------------------------
"if (isset($_POST['guestkey']))\r\n"
"{\r\n"
"	global $unixtime,$logfile,$adminkey,$lang;\r\n"//исправить logfile
"	$gkey=trim($_POST['guestkey']);\r\n"
"	if($gkey=='')return accessForm('',true,true);\r\n"
"	$resp='processed';\r\n"
"	$t=10;if($cmd=='upload_transponder'||$cmd=='loadfromhost'||$cmd=='LOADFROMHOST')$t*=2;\r\n"
" if($access=='')\r\n"
" {\r\n"
"	  if($gkey==trim($adminkey))\r\n"
"	  {\r\n"
"		  if($cmd=='' && $arg=='' && $ext=='')return accessForm(transl('input command'),true,true,true);\r\n"
"	  }\r\n"
"	  else $cmd='open';\r\n"
"	  $r1=save_request_to_file($logfile,$gkey,$cmd,$arg,$ext);\r\n"
"	  if('success'!=$r1)return accessForm($r1=='error:repeat'?transl(speed_joke()):transl($resp),\r\n"
"				true,$r1=='error:repeat'?false:true,$gkey==$adminkey?true:false);\r\n"
"	  check_if_file_correct($logfile);\r\n"
" }\r\n"				
"	while($resp=='processed' && $t>0)\r\n"
"	{\r\n"
"		sleep (1);$t--;\r\n"
"		$resp=get_response_from_file($logfile,$gkey,$unixtime);\r\n"
"		if($resp=='not found')return  accessForm(transl('no reply received.retry.'),false,false,$gkey==$adminkey?true:false);\r\n"
"	}\r\n"
"	return accessForm($resp=='error:repeat'?transl(speed_joke()):transl($resp),true,true,$gkey==$adminkey?true:false);\r\n"
"}\r\n"
"else return accessForm('',true,true);\r\n"
//-----------------------------------
"function speed_joke()\r\n"
"{\r\n"
"	$i=5;\r\n"//mt_rand(0,4);\r\n"
"	switch($i)\r\n"
"	{\r\n"
"		case 0:return 'Estonian server - no way faster.';\r\n"
"		case 1:return 'Hello! Do you believe in God?';\r\n"
"		case 2:return \"We've rated your speed.\";\r\n"
"		case 3:return 'Slow down - bend the button :)';\r\n"
"		default:break;\r\n"
"	}\r\n"
"	return 'do you like speed?';\r\n"
"}\r\n"
//-----------------------------------
"function replace_line_in_file($_file,$index,$line)\r\n" 
"{\r\n"
"	if(!file_exists($_file))if(create_file($_file)!='success')return 'error';\r\n"
"	$lines = file($_file);\r\n" // Считываем весь файл в массив
"	if($index>=count($lines))return 'error';\r\n"
"	$fp = fopen($_file, 'wb');\r\n"// Открываем файл в режиме записи
"	if(!$fp || !flock($fp, LOCK_EX))return 'error';\r\n"
"	$lines[$index]=$line;\r\n"
"	for($i=0;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		$sl=trim($lines[$i]);\r\n"
"		fwrite($fp,$sl.PHP_EOL);\r\n"
"	}\r\n"
"	flock($fp, LOCK_UN);fclose($fp);return 'success';\r\n"
"}\r\n"
//-----------------------------------
"function delete_line_in_file($_file,$line)\r\n" 
"{\r\n"
"	if(!file_exists($_file))return 'no file';\r\n"
"	$lines = file($_file);\r\n" // Считываем весь файл в массив
"	$fp = fopen($_file, 'wb');\r\n"// Открываем файл в режиме записи
"	if(!$fp || !flock($fp, LOCK_EX))return 'error';\r\n"

"	for($i=0;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		if($lines[$i]==$line)\r\n"
"		{\r\n"
"			unset($lines[$i]);$lines = array_values($lines);\r\n"// Переиндексация
"			for($i=0;$i<count($lines);$i++)\r\n"
"			{\r\n"
"				$sl=trim($lines[$i]);\r\n"
"				fwrite($fp,$sl.PHP_EOL);\r\n"
"			}\r\n"
"			flock($fp, LOCK_UN);fclose($fp);return 'success';\r\n"
"		}\r\n"
"	}\r\n"
"	flock($fp, LOCK_UN);fclose($fp);return 'not found';\r\n"
"}\r\n"
//-----------------------------------
"function check_if_file_correct($_file)\r\n" 
"{\r\n"
"	global $logline;\r\n"
"	if(!file_exists($_file))return 'no file';\r\n"
"	$lines = file($_file);\r\n" // Считываем весь файл в массив
"	$del=false;\r\n"
"	for($i=(int)$logline;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		if(strripos($lines[$i],'key=')===false || strripos($lines[$i],'unixtime=')===false)\r\n"//не найдено одно из значений
"		{\r\n"
"			unset($lines[$i]);$lines = array_values($lines);\r\n"
"			$i--;$del=true;\r\n"
"		}\r\n"
"	}\r\n"
	
"	if($del==false)return 'success';\r\n"
	
"	$fp = fopen($_file, 'wb');\r\n"// файл только для записи; помещает указатель в начало файла и обрезает файл до нулевой длины
"	if(!$fp || !flock($fp, LOCK_EX))return 'error';\r\n"
"	for($i=0;$i<count($lines) && $del==true;$i++)\r\n"
"	{\r\n"
"		$sl=trim($lines[$i]);\r\n"
"		fwrite($fp,$sl.PHP_EOL);\r\n"
"	}\r\n"

"	flock($fp, LOCK_UN);fclose($fp);return 'success';\r\n"
"}\r\n"
//-----------------------------------
"function get_var($_line,$_var)\r\n"//получить значение переменной
"{\r\n"
"	$b=strripos($_line,$_var.'=');\r\n"
"	if($b===false)return '';\r\n"
"	else\r\n" 
"	{\r\n"
"		$e=strripos($_line,';',$b);if($e===false)return '';\r\n"
"		$b+=strlen($_var.'=');\r\n"
"		return substr($_line,$b,$e-$b);\r\n"// : string
"	}\r\n"
"}\r\n"
//-----------------------------------
"function put_line_to_file($_file,$line)\r\n" 
"{\r\n"
"	global $tzone,$maxlogs,$logline;\r\n"
"	if(!file_exists($_file))if('success'!=create_file($_file))return 'error';\r\n"
"	$lines = file($_file);\r\n"
"	$len=count($lines);if($len==0)return 'error';\r\n"
"	$last=(count($lines)>=$logline?$lines[count($lines)-1]:'');\r\n"
"	if($last!='')\r\n"
"	{\r\n"
"		$l_unixtime=get_var($last,'unixtime');$l_key=get_var($last,'key');\r\n"
"		if($l_unixtime!='' && $l_key!='' && ((int)get_var($line,'unixtime')-(int)$l_unixtime<=3) && get_var($line,'key')==$l_key)\r\n"
"			return 'error:repeat';\r\n"
"	}\r\n"
"	$fp = fopen($_file, 'wb');\r\n"//запись с уничтожением
"	if(!$fp || !flock($fp, LOCK_EX))return 'error';\r\n"
"	$lines[]=$line;\r\n"
"	for($i=(int)$logline;$i<count($lines) && count($lines)>$maxlogs;$i++)\r\n"
"	{\r\n"
"		unset($lines[$i]);$lines = array_values($lines);\r\n"// Переиндексация
"	}\r\n"
		
"	for($i=0;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		$sl=trim($lines[$i]);\r\n"
"		fwrite($fp,$sl.PHP_EOL);\r\n"
"	}\r\n"
		
"	flock($fp, LOCK_UN);fclose($fp);return 'success';\r\n"
"}\r\n"
//-----------------------------------
"function create_file($_file)\r\n" 
"{\r\n"
"	global $tzone,$maxlogs,$logline,$adminkey,$lang;\r\n"
		
"	if(file_exists($_file))return 'success';\r\n"
"	$fp = fopen($_file, 'wb');if(!$fp || !flock($fp, LOCK_EX))return 'error';\r\n"
"	for($i = 0; $i < $logline; $i++)\r\n"
"	{\r\n"
"		$sline='';\r\n"
"		if($i==0)$sline=$tzone.';'.$maxlogs.';'.$logline.';'.$adminkey.';'.$lang;\r\n"
"		fwrite($fp, $sline);\r\n"
"	}\r\n"
"	flock($fp, LOCK_UN);fclose($fp);return 'success';\r\n"
"}\r\n"
//-----------------------------------
"function save_request_to_file($_file,$_key,$_cmd,$_arg,$_ext)\r\n" 
"{\r\n"
"  global $unixtime,$reqtime;\r\n"
"	if($_key=='')return 'error';\r\n"
"	$str='key='.$_key.';cmd='.$_cmd;\r\n"
"	if($_arg!='')$str=$str.';arg='.$_arg;\r\n"
"	if($_ext!='')$str=$str.';ext='.$_ext;\r\n"
"	$str=$str.';unixtime='.$unixtime.';reqtime='.$reqtime;\r\n"
"	return put_line_to_file($_file,trim($str)) ;\r\n"
"}\r\n"
//-----------------------------------
"function get_request_from_file($_file,$_set_processed=false)\r\n"//получить запрос [и отметить как обработанный]
"{\r\n"
"  global $logline,$reqtime,$key,$dev;\r\n"
"	if($key!=$dev)return AD;\r\n"
"	if(!file_exists($_file))return 'empty';\r\n"//нет файла
"	$lines = file($_file);\r\n"
"	for($i=(int)$logline;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		$pos = strripos($lines[$i],'response=');\r\n"
"		if($pos===false)\r\n"//еще не обработан
"		{\r\n"
"			$str_out=trim($lines[$i]);\r\n"//выходная строка
"			if($_set_processed)if('success'!=replace_line_in_file($_file,$i,$str_out.';response=processed;time='.$reqtime))return 'error' ;\r\n"
"			//echo '<br>$str_out='.trim($lines[count($lines)-1]).'<br>';\r\n"
"			return $str_out ;\r\n"
"		}\r\n"
"	}\r\n"
"	return 'empty';\r\n"
"}\r\n"
//-----------------------------------
"function delete_request_in_file($_file,$ukey,$arg)\r\n"
"{\r\n"
"  global $logline,$reqtime,$key,$dev;\r\n"
"  if($key!=$dev)return AD;\r\n"
"  if(!file_exists($_file))return 'error';\r\n"
"  $lines = file($_file);\r\n"
"  $_ukeyz=str_replace('_',' ',$$_ukey);\r\n"
"  for($i=(int)$logline;$i<count($lines);$i++)\r\n"
"  {\r\n"
"    if((strripos($lines[$i],'key='.$_ukey)!==false || strripos($lines[$i],'key='.$_ukeyz)!==false)&&\r\n"
"      strripos($lines[$i],'unixtime='.$_unixtime)!==false && strripos($lines[$i],'response=')===false)\r\n"
"    {\r\n"
"      return delete_line_in_file($_file,$i);\r\n"
"    }\r\n"
"  }\r\n"
"  return 'not found';\r\n"
"}\r\n"
//-----------------------------------
"function set_response_in_file($_file,$_ukey,$_unixtime,$_response)\r\n"
"{\r\n"
"	global $logline,$reqtime,$key,$dev;\r\n"
"	if($key!=$dev)return AD;\r\n"
"	if(!file_exists($_file))return 'error';\r\n"//нет файла
"	$lines = file($_file);\r\n"
"	$_ukeyz=str_replace('_',' ',$$_ukey);\r\n"
"	for($i=(int)$logline;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		if((strripos($lines[$i],'key='.$_ukey)!==false || strripos($lines[$i],'key='.$_ukeyz)!==false) &&\r\n" 
"					strripos($lines[$i],'unixtime='.$_unixtime)!==false && strripos($lines[$i],'response=')===false)\r\n"
"		{\r\n"
"			if('success'!=replace_line_in_file($_file,$i,trim($lines[$i]).';response='.$_response.';time='.$reqtime))return 'error' ;else return 'success';\r\n" 
"		}\r\n"			
"	}\r\n"
"	return 'not found';\r\n"
"}\r\n"
//-----------------------------------
"function get_response_from_file($_file,$_key,$_unixtime)\r\n"
"{\r\n"
"	global $logline;\r\n"
"	if(!file_exists($_file))return 'not found';\r\n"//нет файла
"	$lines = file($_file);\r\n"
"	for($i=(int)$logline;$i<count($lines);$i++)\r\n"
"	{\r\n"
"		if(strripos($lines[$i],'key='.$_key)!==false && strripos($lines[$i],'unixtime='.$_unixtime)!==false)\r\n"
"		{\r\n"
"			$var=get_var($lines[$i],'response');\r\n"
"			if($var=='')return 'processed';\r\n"//обрабатыватся
"			return $var;\r\n"
"		}\r\n"			
"	}\r\n"
"	return 'not found';\r\n"//возможно,строка была затерта другими запросами,т.к. лог смещается вверх
"}\r\n"
//-----------------------------------
"function dev_name()\r\n"
"{\r\n"
"	$n1=basename(__FILE__);\r\n" 
"	$n2=substr ($n1,0,strlen($n1)-strlen('.php'));\r\n"
"	return $n2;\r\n"
"}\r\n"
//-----------------------------------
"function accessForm($str=null,$_input=false,$_button=false,$_admin=false){\r\n" 
"?>\r\n"
"<html><body bgcolor='#000000'>\r\n" 
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
"<style type=\"text/css\">\r\n"
".stxt{\r\n"
"height: 12%;\r\n" 
"width: 100%;\r\n" 
"font-size: 300%;\r\n" 
"text-align: center;\r\n"
"}\r\n"
"._in{\r\n"
"height: 8%;\r\n"
"width: 40%;\r\n"
"background: #010000;\r\n"
"border: 5% solid #0f0f;\r\n"
"text-align: center;\r\n"
"font-size: 300%;\r\n"
"color: rgb(200, 109, 0);\r\n"
"line-height: 50%;\r\n"
"}\r\n"
".sbutton{\r\n"
"height: 10%;\r\n"
"width: 30%;\r\n"
"background: #000066;\r\n"
"border: 2% solid #0000;\r\n"
"text-align: center;\r\n"
"vertical-align: baseline;\r\n"
"font-size: 300%;\r\n" 
"color: rgb(255,0,0);\r\n"
"line-height: 50%;\r\n"
"}\r\n"
" </style>\r\n"	
" <form align=\"center\" action= <?php echo dev_name().'.php' ?> method= \"post\">\r\n" 
" <p class='stxt' style='color:rgb(255,0,0)' ><br><?php if($str==null)echo dev_name().' v:'.TRANSPONDER_VERSION ?></p>\r\n"
" <p class='stxt' style='color: rgb(155,50, 200)' ><?php echo ((string)$str!=(string)''?$str:strtoupper(transl('ENTER ACCESS KEY'))) ?></p>\r\n"
" <?php //echo '<br>admin='.$_admin;\r\n"
" if($_input==true || $_admin==true) echo \"<p><input class='_in' type= 'text' name= 'guestkey' maxlength='16' autofocus></p>\"  ?>\r\n"
" <?php if($_admin==true) echo \"<p><input class='_in' type='text' name='access' value= 'transfer'><input class='_in' type='text' name='cmd' value= 'cmd'>\\r\n"
" <input class='_in' type='text' name='arg' value='arg'><input class='_in' type='text' name='ext' value='ext'></p>\" ?>\r\n"
" <?php if($_button==true || $_admin==true) echo \"<input class='sbutton' type= 'submit' value= 'SEND' >\"  ?>\r\n"
" </body></html>\r\n"
" <?php ;} \r\n"
"?>\r\n";
//-----------------------------------
/*
https://www.000webhost.com/: https://rvscodeservice.000webhostapp.com/ Inferno13
Имя хоста:files.000webhost.com
Порт:21
Пользователь: rvscodeservice
Пароль:Такой же как пароль сайта
*/
//ERRORS : найти ,Notice:,Parse error:,500 Internal Server Error,
//-----------------------------------
